language: ruby
addons:
  codeclimate:
    repo_token: 22840649ef0d6a85c80f7276acbb377b5baee4938f1d15741f34627245c84c92
# take out rails version lines?
gemfile:
  - 'gemfiles/rails3.gemfile'
  - 'gemfiles/rails4.gemfile'
  - 'Gemfile'
env: RAILS_ENV=test
rvm:
  - 2.3.1
  - 1.9.3
matrix:
  exclude:
  #- rvm: 1.9.3 example
  #  env: 'RAILS_VERSION=4.2.6'
script:
  - bundle exec rails db:drop db:create db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec
notifications:
  email:
    on_success: never
    on_failure: change
    recipients: programmers@admin.umass.edu
