language: ruby
rvm:
  - 2.3.1
  - 1.9.3
  - ruby-head 
addons:
  codeclimate:
    repo_token: 22840649ef0d6a85c80f7276acbb377b5baee4938f1d15741f34627245c84c92
env: RAILS_ENV=test
before_script:
  - bin/rails g install microservices-engine
  - bundle exec rails db:create db:migrate
script:
  - bundle exec rspec
notifications:
  email:
    on_success: never
    on_failure: change
    recipients: programmers@admin.umass.edu

# rails versions: 3.2.21, 4.2.6, 5.0.1
