language: ruby
rvm: 2.3.1
addons:
  codeclimate:
    repo_token: 22840649ef0d6a85c80f7276acbb377b5baee4938f1d15741f34627245c84c92
env: RAILS_ENV=test
before_script:
  - bundle exec rake db:create db:migrate
script:
  - bundle exec rspec
notifications:
  email:
    on_success: never
    on_failure: change
    recipients: programmers@admin.umass.edu
